on:
  workflow_dispatch: {}
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - name: deps
        run: |
          sudo apt -y update
          sudo apt -y install build-essential autoconf automake libtool pkg-config flex bison gettext uuid-dev libblkid-dev zlib1g-dev
      - name: build
        run: |
          bash build.sh
      - uses: actions/upload-artifact@v4
        with:
          name: parted
          path: parted-3.6/parted/parted
      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: parted-3.6/parted/parted
          asset_name: parted
          tag: v3.6
          overwrite: true
          body: 'parted 3.6'
